### ISSUE TITLE
Can't preview the cards

### ISSUE THREAD

**Issue by ram535** [chenyanming/anki.el#1]
When press `RET` 
![image](https://user-images.githubusercontent.com/9011002/93199832-be6d0600-f703-11ea-9927-04bf02b5f637.png)

**Comment by chenyanming** [comment]
Add cl-lib, should fix.

**Comment by ram535** [comment]
I updated the package but it did not work. It throw the same error.

**Comment by chenyanming** [comment]
May I know what errors you saw?

**Comment by chenyanming** [comment]
What Emacs version and OS system you used?

**Comment by ram535** [comment]
GNU Emacs 28.0.50
Linux Mint 19.3

**Comment by chenyanming** [comment]
Can you try `M-x anki-find-card-at-point`, is the card information printed?  `mapcar*` is from package `cl-lip`, would you try `(require 'cl-lib)`, and press RET again?

**Comment by chenyanming** [comment]
If still can not work, would you help try the last thing?
`(setq debug-on-error t)`, then press `RET`, and copy the detailed error message to me?

**Comment by ram535** [comment]
`M-x anki-find-card-at-point` did not show any message.

`(require 'cl-lib)` did not work. 

```
Debugger entered--Lisp error: (void-function mapcar*)
  mapcar*(cons ("Front" "Back" "Audio") ("<p>\nI'm tired because I worked a lot.\n[sound:2-bfd..." "<p>\nIch bin müde, weil ich viel gearbeit habe.\n</p..." "<p>\n[sound:1-dbdfaa459fe1a8efe2c8892e62d0a45d1fa30..."))
  anki-show-card(#<hash-table equal 30/65 0x15567e493135> :switch)
  anki-preview-card()
  funcall-interactively(anki-preview-card)
  call-interactively(anki-preview-card nil nil)
  command-execute(anki-preview-card)
```

**Comment by chenyanming** [comment]
New commit should fix. `mapcar*` is deprecated. I changed to `cl-mapcar`
https://github.com/JorisE/yapfify/commit/0b4f20af0b00a86353ddc286df26eade89381269

**Comment by ram535** [comment]
I confirm that the new commit fix the problem. Thanks.
