### ISSUE TITLE
Modifying the original anki database

### ISSUE THREAD

**Issue by eshrh** [chenyanming/anki.el#10]
Why doesn't anki.el modify the original anki database? What work needs to be done to make it happen? I think that being able to use both anki.el and the official Anki app would be really awesome.

**Comment by chenyanming** [comment]
It is possible but difficult, the difficulty is on the flashcard review algorithm.

**Comment by chenyanming** [comment]
Now I only implemented my own SM2 algorithm.

**Comment by chenyanming** [comment]
Modify cards are possible, using reverse engineering and comparing the card changes. But it is also a big task.

**Comment by chenyanming** [comment]
I hope someone can help, it is not an easy task.

**Comment by eshrh** [comment]
Ok, thank you so much!
