### ISSUE TITLE
Stop working after updating

### ISSUE THREAD

**Issue by ram535** [chenyanming/anki.el#2]
`M-x anki` throw this message `json-read: JSON readtable error: 2`.

Debugging:

(setq debug-on-error t)
```
Debugger entered--Lisp error: (json-readtable-error 2)
  signal(json-readtable-error (2))
  json-read()
  json-read-from-string("\2")
  anki-parse-decks()
  anki-parse-cards()
  anki-format-cards()
  anki()
  funcall-interactively(anki)
  call-interactively(anki record nil)
  command-execute(anki record)
  execute-extended-command(nil "anki" nil)
  funcall-interactively(execute-extended-command nil "anki" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by chenyanming** [comment]
Would you help run

` (anki-query anki-query-decks)` and copy the results to me?

**Comment by chenyanming** [comment]
Is `anki-browser` stop working as well?

**Comment by ram535** [comment]
`anki-browser` is not working either.

`(anki-query anki-query-decks)` result `"^B"`

**Comment by chenyanming** [comment]
Would you try run 
`sqlite3 collection.anki2.el "SELECT decks FROM col"` under the collection folder? Besides, I tempory made a fix 4f1b68a.

**Comment by chenyanming** [comment]
Since official Anki Client will lock the database when it opens, which make me can not read the database. Copy the database is for temporary reading.

**Comment by ram535** [comment]
I run `sqlite3 collection.anki2 "SELECT decks FROM col"` but I do not have idea for what it is for?
![image](https://user-images.githubusercontent.com/9011002/93712730-84896e80-fb0c-11ea-86ab-71d451888621.png)
I did not show any output. I mean I do not know if I should expect any output.

> Since official Anki Client will lock the database when it opens, which make anki.el can not read the database. Copy the database is for temporary reading.

Sorry I do not know what you mean. Should I copy the database?

After updating, the error did not disappear.

**Comment by chenyanming** [comment]
Seems your database does not have the decks data, since `col` column saves the decks information. It would be helpful if you share the database to me to further study.

**Comment by chenyanming** [comment]
I mean Anki.el copies the database to temp folder and read the copied file. Anki.el does not read the original database file.

**Comment by ram535** [comment]
I see, here is the database.

[collection.anki2.zip](https://github.com/chenyanming/anki.el/files/5252065/collection.anki2.zip)

**Comment by ram535** [comment]
I used https://github.com/louietan/anki-editor to add content to my decks. To be able to add content to the decks, anki has to open and have the https://github.com/FooSoft/anki-connect#installation plugin.

**Comment by chenyanming** [comment]
One note here, if anki keeps open, it will lock the database, and any modification saves to a `wal` and a `shm` file. Only you close anki, the changes will be saved to `collection.anki2`. 

`anki.el` only reads the copy of `collection.anki2`.

I can not find a realible way to handle the `wal` and `shm` files so far. Therefore, if you want the changes applied and shown in `anki.el`, you have to close anki.

**Comment by chenyanming** [comment]
Since the database can not sync between anki.el and anki, it is difficult for me to handle some anki original data, such as the review logs.

Anki is very complicated and big, which makes people can not easily implement the features. I am not a fan of the original anki client. Therefore, anki.el will go lighter and will implement its own review feature. Anki is only providing the database.

Actually, I already implemented the anki-connect feature to control the anki client to show and anwer the card. But anki connect is very slow, and keeps anki opening makes me distracted...

**Comment by ram535** [comment]
Nice, I like your approach. I am not a elisp hacker but if you need help testing stuff, I would gladly help.

When I have tested `M-x anki`, anki was not opened.

Have you checked https://github.com/l3kn/org-fc, I think it has more futures than org-drill. For example org-fc has input cards (you type the answer) similar as anki does it.

**Comment by chenyanming** [comment]
I am really happy that you provide supports and help!

By the way, I tested your `collection.anki2`, seems it is corrupted, or may not supported in new anki?. Which version of anki are you using? I am using Anki Version 2.1.15 (442df9d6).

![Screenshot 2020-09-21 at 09 53 42](https://user-images.githubusercontent.com/3462132/93728069-de636480-fbf0-11ea-9256-082ba4fa8dcb.png)

I recommend you use the latest anki client to regenerate the database.

**Comment by chenyanming** [comment]
Or maybe the database format is too new....Your `collection.anki2` version is 15. Mine is 11. Let me check...

**Comment by chenyanming** [comment]
I follow the https://github.com/ankidroid/Anki-Android/wiki/Database-Structure

**Comment by chenyanming** [comment]
I checked. Anki did change the database format in later versions.
https://changes.ankiweb.net/#/
```
Changes
warning After using the latest version, if you wish to open your collection with an earlier Anki release, please go to the File>Switch Profile menu item, and click on “Downgrade & Quit”. If you skip this step, you may get an error message when opening your collection in an older Anki version, and you will need to return to this version, downgrade, then try again.
```

**Comment by chenyanming** [comment]
You have to downgrade the anki database and check again.

https://forums.ankiweb.net/t/json-decoder-jsondecodeerror-expecting-value-line-1-column-1-char-0/622/3

For latest database format, I may wait the stable anki client version come out first. Since the database is still new and does not have enough document for me to integrate.

**Comment by ram535** [comment]
Indeed that was the problem. I was using anki version `2.1.33`.

But it seems I do not need to install an older version.

If I do `File>Switch Profile menu item, and click on “Downgrade & Quit”`.
`M-x anki` works fine.

**Comment by hpfr** [comment]
Could you post here or cut a release when the new database format is supported? I think I'd rather use the Anki app and wait until anki.el supports the new database format than have to downgrade my database.

Thanks for your work on this package!

**Comment by czqhurricnae** [comment]
确实很糟糕，这个包不支持哪个版本的 Anki 应该在 README 写清楚。花时间装上发现不支持，就是浪费时间了。
