### ISSUE TITLE
Audio is not working

### ISSUE THREAD

**Issue by ram535** [chenyanming/anki.el#3]
When a card with audio is open, just noise comes as audio.

Is this correct `(setq anki-audio-player (or (executable-find "aplay") (executable-find "afplay")))`?

`(executable-find "aplay")` is repeat twice.

`(executable-find "aplay")`
=>  "/usr/bin/aplay"

**Comment by chenyanming** [comment]
This is an example of find `aplay` or `afplay`, but you have to make sure either one is installed before playing audio. You can use other tools actually, maybe `mpv` or `mplayer` which should sit in the system path.

For example, set with 
```
(setq anki-audio-player "mpv"))
```

**Comment by ram535** [comment]
It seems I am kind of blind, I did not see the difference betwwen `aplay` and `afplay`.
`(setq anki-audio-player "mpv")` that works.
